substitutions:
  name: cativoclimatev2
  friendly_name: Cativo Climate

  division_1: "Bathroom"
  division_2: "Bedroom"
  division_3: "Office"
  division_4: "Living Room"
  division_id_1: "bathroom"
  division_id_2: "bedroom"
  division_id_3: "office"
  division_id_4: "livingroom"

  #### Env Temperature sensors average parameters
  window_size: "10"
  send_every: "5"
  send_first_at: "1"

  heatpump_power_id: "switch.heatpump_power_switch"

globals:
  - id: mixer_output_level
    type: float
    restore_value: true
    initial_value: '0.0'


esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.33.194
    gateway: 192.168.33.1
    subnet: 255.255.255.0
    dns1: 192.168.33.1

# Enable logging
logger:

# Enable Home Assistant API
#api:

# Allow Over-The-Air updates
ota:
- platform: esphome

# Allow provisioning Wi-Fi via serial
improv_serial:

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# To have a "next url" for improv serial
web_server:
  version: 3
  sorting_groups:
    - id: sort_group_thermostats
      name: "Thermostats"
      sorting_weight: -10
    - id: sort_group_water_circuit
      name: "Water Circuit"
      sorting_weight: -9
    - id: sort_group_temperature_sensors
      name: "Temperature Sensors"
      sorting_weight: -8
    - id: sort_group_settings
      name: "Settings"
      sorting_weight: -7
    - id: sort_group_status
      name: "Status"
      sorting_weight: 100


<<: !include cativoclimatev2/hwsetup.yaml
<<: !include cativoclimatev2/outputs.yaml
<<: !include cativoclimatev2/display.yaml
<<: !include cativoclimatev2/sensors.yaml
<<: !include cativoclimatev2/binary_sensors.yaml
<<: !include cativoclimatev2/switches.yaml
<<: !include cativoclimatev2/climate.yaml
<<: !include cativoclimatev2/selects.yaml