- platform: thermostat
  ### SETUP
  name: ${division_${nr}} Temperature Control
  id: ${name}_${division_id_${nr}}_thermostat
  sensor: ${division_id_${nr}}_temperature
  ### PRESETS
  preset:
    - name: home
      default_target_temperature_low: ${def_temp_low}
      default_target_temperature_high: ${def_temp_high}
      mode: heat
    - name: away
      default_target_temperature_low: ${def_away_temp_low}
      default_target_temperature_high: ${def_away_temp_high}
      mode: heat
    - name: "home cool"
      default_target_temperature_low: ${def_temp_low}
      default_target_temperature_high: ${def_temp_high}
      mode: cool
    - name: "away cool"
      default_target_temperature_low: ${def_away_temp_low}
      default_target_temperature_high: ${def_away_temp_high}
      mode: cool
  ### Tunning parameters
  default_preset: home
  heat_deadband: ${def_deadband}
  heat_overrun: ${def_overrun}
  cool_deadband: ${def_deadband}
  cool_overrun: ${def_overrun}
  min_idle_time: ${def_min_idle_time}
  min_cooling_off_time: ${def_min_cooling_off_time}
  min_cooling_run_time: ${def_min_cooling_run_time}
  min_heating_off_time: ${def_min_heating_off_time}
  min_heating_run_time: ${def_min_heating_run_time}
  ### ACTIONS
  off_mode:
    - switch.turn_off: ${name}_${division_id_${nr}}_valve
  heat_mode:
    - script.execute: set_mode_heat
  cool_mode:
    - script.execute: set_mode_cool
  auto_mode:
    - script.execute: set_mode_heat
  cool_action:
    - script.wait: set_mode_cool
    - switch.turn_on: ${name}_${division_id_${nr}}_valve
  heat_action:
    - script.wait: set_mode_heat
    - switch.turn_on: ${name}_${division_id_${nr}}_valve
    # - lambda: |-
    #     float out = 0.0;
    #     out = (${name}_${division_id_${nr}}_valve.target_temperature_low - ${division_id_${nr}}_temperature.state) * id(PID_setup_kp).state
    #     id(${name}_${division_id_${nr}}_pwm_control).set_level(out);
  idle_action:
    - switch.turn_off: ${name}_${division_id_${nr}}_valve
    # - lambda: |-
    #     id(${name}_${division_id_${nr}}_pwm_control).set_level(division_pwm_min_power);

- platform: pid
  ### SETUP
  # name: ${division_${nr}} PID Control
  # id: ${division_id_${nr}}_pid_control
  name: ${division_${nr}} Temperature Control
  id: ${name}_${division_id_${nr}}_thermostat
  sensor: ${division_id_${nr}}_temperature
  default_target_temperature: ${def_temp_low}
  heat_output: ${name}_${division_id_${nr}}_pwm_control
  cool_output: dummy_cool_pwm
  control_parameters:
    kp: ${kp}
    ki: ${ki}
    kd: ${kd}
    min_integral: -0.1
    max_integral: 0.5
    output_averaging_samples: 2 # smooth the output over 5 samples
    derivative_averaging_samples: 3 # smooth the derivative value over 10 samples

  ### Tunning parameters
  deadband_parameters:
    threshold_high: 0.1°C #### Deve ser 0,1 e -0,1??????
    threshold_low: -0.1°C
    deadband_output_averaging_samples: 5
  icon: mdi:thermostat
  web_server:
    sorting_group_id: sort_group_temperature_sensors
    sorting_weight: ${nr}