---
#- platform: xiaomi_lywsd03mmc
- platform: pvvx_mithermometer
  mac_address: ${mac}
#  bindkey: ${bkey}
  temperature:
    name: ${division_${nr}} Temperature
    id: ${division_id_${nr}}_temperature
    accuracy_decimals: 2
    filters:
      - sliding_window_moving_average:
          window_size: ${window_size}
          send_every: ${send_every}
          send_first_at: ${send_first_at}
  humidity:
    name: ${division_${nr}} Humidity
  battery_level:
    name: ${division_${nr}} Sensor Battery