esphome:
  name: ${name}
  platform: ESP32
  board: m5stack-atom
  # on_boot:
  #   - sensor.template.publish:
  #       id: log_errors
  #       state: 0
  # on_boot:
  #   priority: -100
  #   then:
  #     - climate.control:
  #         id: "${division_id_1}_temperature_control"
  #         mode: "OFF"

logger:
  level: DEBUG
  # on_message:
  #   level: ERROR
  #   then:
  #     - sensor.template.publish:
  #         id: log_errors
  #         state: !lambda |-
  #           int errors = id(log_errors).state;
  #           errors = errors + 1;
  #           return errors;

wifi:
  ssid: birelesha
  password: montecativo256
  manual_ip:
    static_ip: 192.168.33.90
    gateway: 192.168.33.1
    subnet: 255.255.255.0
    dns1: 192.168.33.1

# Enable Home Assistant API
api:

ota:
  - platform: esphome

# http_request:
#   useragent: esphome/device
#   timeout: 15s

# web_server:
#   port: 80

# --------------- Only needed for screen -------------
# spi:
#   clk_pin: 18
#   mosi_pin: 23
#   miso_pin: 19

i2c:
  # - id: bus_a
  #   sda: 26
  #   scl: 32
  #   scan: False
  - id: bus_b
    sda: 19
    scl: 22
    scan: False

pcf8574:
  - id: "hub_relays"
    address: 0x27
    pcf8575: False
  - id: "hub_sensors"
    address: 0x20
    pcf8575: False

esp32_ble_tracker:
  scan_parameters:
    active: True

one_wire:
  - platform: gpio
    pin: GPIO25
    id: dallas_1
# light:
#   - platform: fastled_clockless
#     chipset: WS2812B
#     pin: 27
#     num_leds: 1
#     rgb_order: GRB
#     id: ${name}_status_led
#     name: ${name} LED
#     effects:
#       - random:
#       - flicker:
#       - addressable_rainbow:

http_request:
  useragent: esphome/device
  timeout: 10s
  verify_ssl: false